[theme]
base = "light"
primaryColor = "#2F5353"
backgroundColor = "#FAF4E8"
secondaryBackgroundColor = "#FEFBF5"
textColor = "#162526"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
