[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#f3f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1526"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
